Only require types from /common on the server
I'm working on debugging this, but for the time being this should fix some
errors that are popping up on the server:

```
Error: Cannot find module 'common/challenge'
```